#!/bin/sh
set -e

bundle${RUBY_VER}
bundle-audit${RUBY_VER} --update

yarn
yarn audit

bundle${RUBY_VER} exec rake db:dump
bundle${RUBY_VER} exec rake db:migrate

bundle${RUBY_VER} exec rake assets:clobber assets:precompile

rsync -aL public/. "/var/www/$USER/"
