#!/bin/sh
set -e

. ./config

if ! [ -f .secret-key-base ]; then
    genpassword 64 > .secret-key-base
fi

cd "${SITE}"

echo "$(git rev-parse HEAD) start [preparing]" >> ../deploy.log

export SECRET_KEY_BASE=$(head -n 1 ../.secret-key-base)

/home/scripts/prepare

echo "$(git rev-parse HEAD) start" >> ../deploy.log
bundle${RUBY_VER} exec puma -b "tcp://127.0.0.1:${PORT}"
echo "$(git rev-parse HEAD) stop" >> ../deploy.log
